// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: copyfrom.go

package pgstore

import (
	"context"
)

// iteratorForInviteParticipantsToTrip implements pgx.CopyFromSource.
type iteratorForInviteParticipantsToTrip struct {
	rows                 []InviteParticipantsToTripParams
	skippedFirstNextCall bool
}

func (r *iteratorForInviteParticipantsToTrip) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInviteParticipantsToTrip) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].TripID,
		r.rows[0].Email,
	}, nil
}

func (r iteratorForInviteParticipantsToTrip) Err() error {
	return nil
}

func (q *Queries) InviteParticipantsToTrip(ctx context.Context, arg []InviteParticipantsToTripParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"participants"}, []string{"trip_id", "email"}, &iteratorForInviteParticipantsToTrip{rows: arg})
}
