// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package pgstore

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Activity struct {
	ID       uuid.UUID        `db:"id" json:"id"`
	TripID   uuid.UUID        `db:"trip_id" json:"trip_id"`
	Title    string           `db:"title" json:"title"`
	OccursAt pgtype.Timestamp `db:"occurs_at" json:"occurs_at"`
}

type Link struct {
	ID     uuid.UUID `db:"id" json:"id"`
	TripID uuid.UUID `db:"trip_id" json:"trip_id"`
	Title  string    `db:"title" json:"title"`
	Url    string    `db:"url" json:"url"`
}

type Participant struct {
	ID          uuid.UUID `db:"id" json:"id"`
	TripID      uuid.UUID `db:"trip_id" json:"trip_id"`
	Email       string    `db:"email" json:"email"`
	IsConfirmed bool      `db:"is_confirmed" json:"is_confirmed"`
}

type Trip struct {
	ID          uuid.UUID        `db:"id" json:"id"`
	Destination string           `db:"destination" json:"destination"`
	OwnerEmail  string           `db:"owner_email" json:"owner_email"`
	OwnerName   string           `db:"owner_name" json:"owner_name"`
	IsConfirmed bool             `db:"is_confirmed" json:"is_confirmed"`
	StartsAt    pgtype.Timestamp `db:"starts_at" json:"starts_at"`
	EndsAt      pgtype.Timestamp `db:"ends_at" json:"ends_at"`
}
